#!/bin/sh -eu

################################################################################
# Edit this file and then rename it to ~/.xmonad/build

################################################################################
# The directory holding your source code and Cabal file:
SRC_DIR=~/.config/xmonad

################################################################################
# The name of the executable produced by cabal.  This comes from the
# executable section of your Cabal file.
EXE_NAME=xmonad

################################################################################
# This script will be given a single argument, the path to the
# executable it should produce.
output_file=$1; shift

################################################################################
cd $SRC_DIR

# Build with nix
nix-build shell.nix

# Move the binary out into the root directory
nix-env -i "$SRC_DIR/result"
