#!/usr/bin/env bash

# remove stale branches
set -uo pipefail

git fetch --prune
STALE_BRANCHES=$(git branch -r | awk '{ print $1 }' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin | grep ": gone" | awk '{ print $1 }' | grep -v '\*'))

if [[ -z "${STALE_BRANCHES}" ]]; then
	echo "No stale branches."
else
	echo "${STALE_BRANCHES}" | xargs git branch -D
fi
