#!/usr/bin/env bash

# start an Emacs session in the current directory

set -euo pipefail
SESSION="${1:-"$(basename "${PWD}")"}"

echo "Starting Emacs session ${SESSION}..."
emacs -nw --eval "(setq server-name \"${SESSION}\")" --eval "(server-start)"
