#!/usr/bin/env bash

# External display in 2x scaled native resolution above internal
set -euo pipefail

if xrandr | grep DP-1-1; then
    xrandr --output eDP-1-1 --auto --pos 0x2880 --primary \
	   --output DP-1-2 --mode 2560x1440 --pos 0x0 --scale 2x2 \
	   --output DP-1-3 --off \
	   --output HDMI-1-1 --off
else
    xrandr --output eDP-1 --auto --pos 0x2880 --primary \
	   --output DP-2 --mode 2560x1440 --pos 0x0 --scale 2x2 \
	   --output DP-3 --off \
	   --output HDMI-1 --off
fi
~/.fehbg
