#!/usr/bin/env bash

# Arranges the display layout so the internal display is beneath the external one
set -euo pipefail

if xrandr | grep DP-1-1; then
    xrandr --output eDP-1-1 --primary --auto \
	   --output DP-1-1 --auto --above eDP-1-1 \
	   --output DP-1-2 --auto --above eDP-1-1 \
	   --output DP-1-3 --auto --above eDP-1-1
else
    xrandr --output eDP-1 --primary --auto \
	   --output DP-1 --auto --above eDP-1 \
	   --output DP-2 --auto --above eDP-1 \
	   --output DP-3 --auto --above eDP-1
fi
~/.fehbg
