#!/usr/bin/env bash

# Arranges the display layout so the internal display is beneath the external one
set -euo pipefail

# First set of outputs are for internal graphics, second for when using external graphics.
xrandr --output DP-1 --auto --above eDP-1 \
	--output DP-2 --auto --above eDP-1 \
	--output DP-3 --auto --above eDP-1 \
	--output DP-1-1 --auto --above eDP-1-1 \
	--output DP-1-2 --auto --above eDP-1-1 \
	--output DP-1-3 --auto --above eDP-1-1
~/.fehbg
