#!/usr/bin/env bash

set -euo pipefail

xrandr --output eDP-1 --auto \
	--output DP-1 --off \
	--output DP-2 --off \
	--output DP-3 --off \
	--output HDMI-1 --off \
	--output HDMI-2 --off \
	--output HDMI-3 --off
