#!/usr/bin/env bash

# Internal display only
set -euo pipefail

xrandr --output eDP-1-1 --auto --pos 0x0 \
	--output DP-1-1 --off \
	--output DP-1-2 --off \
	--output DP-1-3 --off \
	--output DP-1-4 --off

~/.fehbg
