#!/usr/bin/env bash

# Internal display only
set -euo pipefail

if xrandr | grep eDP-1-1; then
    xrandr --output eDP-1-1 --primary --auto --pos 0x0 \
	--output HDMI-1 --off \
	--output DP-1-1 --off \
	--output DP-1-2 --off \
	--output DP-1-3 --off \
	--output DP-1-4 --off \
	--output HDMI-1-1 --off
else
    xrandr --output eDP-1 --primary --auto --pos 0x0 \
	   --output DP-1 --off \
	   --output DP-2 --off \
	   --output DP-3 --off \
	   --output DP-4 --off \
	   --output HDMI-1 --off
fi

~/.fehbg
