#!/usr/bin/env bash


# Standard work profile with keyboard and display to the right
set -euo pipefail

if xrandr | grep eDP-1-1; then
xrandr --output eDP-1-1 --mode 3840x2400 --pos 0x0 --primary \
	--output DP-1-1 --off \
	--output DP-1-2 --off \
	--output DP-1-3 --pos 3840x2400 --scale 2x2 \
	--output DP-1-4 --off
else
    xrandr --output eDP-1 --mode 3840x2400 --pos 0x0 --primary \
	   --output DP-1 --off \
	   --output DP-2 --off \
	   --output DP-3 --pos 3840x0 --mode 2560x1440 --scale 2x2 \
	   --output DP-4 --off
fi
~/.fehbg
