#!/bin/sh -eu

################################################################################
# Edit this file and then rename it to ~/.xmonad/build

################################################################################
# The directory holding your source code and Cabal file:
SRC_DIR=~/.xmonad

################################################################################
# The name of the executable produced by cabal.  This comes from the
# executable section of your Cabal file.
EXE_NAME=xmonad

################################################################################
# This script will be given a single argument, the path to the
# executable it should produce.
output_file=$1; shift

################################################################################
cd $SRC_DIR

# Configure the package
nix-shell shell.nix --command "cabal configure \
                     --enable-optimization \
                     --enable-executable-stripping"

# Build the package
nix-shell shell.nix --command "cabal build"

# Move the binary out into the root directory
find dist -type f -executable -name $EXE_NAME \
     -exec mv -u '{}' $output_file ';'

# Remove building
rm -r dist*
