#!/bin/sh -eu

################################################################################
# Edit this file and then rename it to ~/.xmonad/build

################################################################################
# The directory holding your source code and Cabal file:
SRC_DIR=~/.dotfiles/xmonad/src

################################################################################
# The name of the executable produced by cabal.  This comes from the
# executable section of your Cabal file.
EXE_NAME=xmonad

################################################################################
# This script will be given a single argument, the full path to the
# executable it should produce.
output_file=$1; shift

if [ -f "$output_file" ]; then
    rm -f "$output_file"
fi

################################################################################

(
    # Build with nix
    cd "${SRC_DIR}"
    cabal v2-install --bindir "${HOME}/.cabal/bin" --overwrite-policy=always

    # Move the binary out into the root directory
    cp "${HOME}/.cabal/bin/$EXE_NAME" "$output_file"
)
