################################################################################
# Makefile for Jassobs tmux configs
#
# Usage: make tmux
#
# Feel free to use this file or any parts if you find it usable.
#
# Author: Jassob <jassob [at] live [dot] se>
################################################################################
tmux:
	ln -s .tmux.conf ~/
