#!/usr/bin/env bash

# [DEVICE] -- Connect to DEVICE, or list all paired devices if DEVICE is not supplied
set -euo pipefail

DEVICE="${1:-undefined}"

if [[ "${DEVICE}" == "undefined" ]]; then
    DEVICE=$(bluetoothctl devices Paired | sed 's/Device \S* \(\S*\)/\1/' | fzf)
fi

DEVICE_MAC=$(bluetoothctl devices Paired | grep "${DEVICE}" | cut -f 2 -d ' ')
if [[ -z "${DEVICE_MAC}" ]]; then
    echo "${DEVICE} is not a paired device, check spelling or call again without name."
    exit 127
fi

echo "Connecting to ${DEVICE}..."
bluetoothctl connect "${DEVICE_MAC}"
